import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import 'daos/categories_dao.dart';
import 'daos/goals_dao.dart';
import 'daos/transactions_dao.dart';

part 'database.g.dart'; // generated by build_runner — see README

/// Expense/income categories (Food & Drinks, Transport, ...).
///
/// [colorHex] and [monthlyBudget] let the UI render the category's
/// accent color and its budget progress bar directly from this row
/// instead of re-deriving them client-side.
class Categories extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().withLength(min: 1, max: 40)();
  TextColumn get icon => text()(); // Material icon name, e.g. "restaurant"
  TextColumn get colorHex => text()(); // e.g. "FF1FAE8E"
  RealColumn get monthlyBudget => real().withDefault(const Constant(0))();
}

/// A funding source (cash, bank account, mobile money wallet, ...).
class Accounts extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().withLength(min: 1, max: 40)();
  TextColumn get type => text()(); // 'cash' | 'bank' | 'mobile_money'
  RealColumn get balance => real().withDefault(const Constant(0))();
}

/// A single expense or income record.
class Transactions extends Table {
  IntColumn get id => integer().autoIncrement()();
  RealColumn get amount => real()();
  IntColumn get categoryId =>
      integer().references(Categories, #id, onDelete: KeyAction.setNull).nullable()();
  IntColumn get accountId =>
      integer().references(Accounts, #id, onDelete: KeyAction.setNull).nullable()();
  TextColumn get note => text().withDefault(const Constant(''))();
  DateTimeColumn get date => dateTime()();
  // 'expense' | 'income'
  TextColumn get type => text()();
  BoolColumn get isRecurring => boolean().withDefault(const Constant(false))();
}

/// A savings goal with a target amount and a running saved amount.
class Goals extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().withLength(min: 1, max: 60)();
  RealColumn get targetAmount => real()();
  RealColumn get savedAmount => real().withDefault(const Constant(0))();
  DateTimeColumn get startDate => dateTime()();
  DateTimeColumn get targetDate => dateTime()();
  TextColumn get colorHex => text().withDefault(const Constant('FF1FAE8E'))();
}

@DriftDatabase(
  tables: [Categories, Accounts, Transactions, Goals],
  daos: [CategoriesDao, TransactionsDao, GoalsDao],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  /// Bump this whenever a table shape changes, and add a migration step
  /// in [migration] — Drift will not silently alter existing user data.
  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) async {
      await m.createAll();
      await _seedDefaults(this);
    },
  );
}

Future<void> _seedDefaults(AppDatabase db) async {
  await db.batch((batch) {
    batch.insertAll(db.categories, [
      CategoriesCompanion.insert(
        name: 'Food & Drinks',
        icon: 'restaurant',
        colorHex: 'FF1FAE8E',
        monthlyBudget: const Value(1000),
      ),
      CategoriesCompanion.insert(
        name: 'Transport',
        icon: 'directions_car',
        colorHex: 'FFF0A93A',
        monthlyBudget: const Value(200),
      ),
      CategoriesCompanion.insert(
        name: 'Entertainment',
        icon: 'movie',
        colorHex: 'FFE14C4C',
        monthlyBudget: const Value(150),
      ),
      CategoriesCompanion.insert(
        name: 'Bills & Utilities',
        icon: 'receipt_long',
        colorHex: 'FF8B6FE0',
        monthlyBudget: const Value(200),
      ),
      CategoriesCompanion.insert(
        name: 'Shopping',
        icon: 'shopping_bag',
        colorHex: 'FF8B6FE0',
        monthlyBudget: const Value(500),
      ),
      CategoriesCompanion.insert(
        name: 'Income',
        icon: 'arrow_downward',
        colorHex: 'FF2FDCC0',
      ),
    ]);
    batch.insert(
      db.accounts,
      AccountsCompanion.insert(name: 'Main Account', type: 'bank', balance: const Value(50000.90)),
    );
  });
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'expense_tracker.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}